services:
  postgres:
    image: postgres:15-alpine
    container_name: resource_allocation_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: resource_allocation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
